dist:
  name: otelcol-custom
  description: Custom OpenTelemetry Collector
  output_path: ./dist

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.114.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.114.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.114.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.114.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.114.0

connectors: []
