receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  filter/drop_eventstream_spans:
    error_mode: ignore
    traces:
      span:
        - 'IsMatch(attributes["http.url"], ".*EventStream.*")'
  filter/slowspans:
    error_mode: ignore
    traces:
      span:
        # Filter out spans with duration > 1 minute (60 seconds)
        # Duration is calculated as end_time - start_time (both in nanoseconds)
        # 60 seconds = 60000000000 nanoseconds
        - '(end_time_unix_nano - start_time_unix_nano) > 60000000000'

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlphttp:
    endpoint: https://api.honeycomb.io
    headers:
      x-honeycomb-team: ${env:HONEYCOMB_API_KEY}
    retry_on_failure:
      enabled: true
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 8
      queue_size: 2000

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/slowspans, filter/drop_eventstream_spans, batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      exporters: [otlphttp]
